### ISSUE TITLE
Why this happen ?

### ISSUE THREAD

**Issue by afkadev** [sandrokeil/php-to-zephir#3]
[http://prntscr.com/m6zkjz](url)

**Comment by sandrokeil** [comment]
Try to use the full path. Looks like path resolution does not work correctly.

**Comment by afkadev** [comment]
how i must write command
please show me an example

**Comment by sandrokeil** [comment]
For example `php2zephir:zep:create /app/src /app/ext`. Please read the [zephir docs](https://docs.zephir-lang.com/0.11/en/tutorial) to create the extension skeleton first.
